name: Minha Primeira Linha de Montagem

on:
  push:
    branches: [ main ]

jobs:
  construcao:
    runs-on: ubuntu-latest
    steps:
      - name: Coletando o código fonte
        uses: actions/checkout@v4

      - name: Executando tarefa de teste
        run: echo "A linha de montagem funcionou com sucesso!"
